name: SFTP Deploy

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: SFTP Deploy
      uses: Dylan700/sftp-upload-action@latest
      with:
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server: y3hqfr.myvserver.online
        port: 22
        uploads: |
          ./ => ./var/www/formulate-ai
        ignore: |
          *.git
          */**/*git*
          *.idea
          */**/idea

    - name: Run pnpm install
      env:
        SSH_USER: ${{ secrets.FTP_USERNAME }}
        SSH_PASS: ${{ secrets.FTP_PASSWORD }}
        SSH_HOST: y3hqfr.myvserver.online
        SSH_PORT: 22
      run: |
        ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST -p $SSH_PORT "cd /var/www/formulate-ai && pnpm install"
  
