name: SFTP Deploy

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: SFTP Deploy
      uses: Dylan700/sftp-upload-action@latest
      with:
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server: y3hqfr.myvserver.online
        port: 22
        uploads: |
          ./ => ./var/www/formulate-ai
  
